version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "America/Sao_Paulo"
    reviewers:
      - "marechal-dev"
    ignore:
      - dependency-name: "@types/node"
