version: '3.8'

volumes:
  db-data:
    driver: local

services:
  database:
    image: bitnami/postgresql:15
    container_name: "adoptgram-social-pg-db"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=adoptgram_social
    volumes:
      - 'db-data:/bitnami/postgresql'
  
  queue:
    image: bitnami/redis:7.0
    container_name: "adoptgram-social-redis-queue"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  dev:
    build:
      context: .
      dockerfile: "dev.Dockerfile"
    ports:
      - 3000:3000
    depends_on:
      - database
      - queue
    volumes:
      - .:/usr/app

  # prod:
  #   build: "./.docker/prod"
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
