version: '3.8'

volumes:
  cache_data:
    driver: local
  db-data:
    driver: local

services:
  database:
    image: bitnami/postgresql:15
    container_name: 'adoptgram-social-postgresql-db'
    restart: always
    profiles:
      - 'dev'
      - 'prod'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=adoptgram_social
    volumes:
      - 'db-data:/bitnami/postgresql'

  cache:
    image: redis
    container_name: 'adoptgram-social-redis-cache'
    profiles:
      - 'dev'
      - 'prod'
    ports:
      - 6379:6379
    volumes:
      - 'cache_data:/data'

  # dev:
  #   container_name: 'adoptgram-social-dev'
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   profiles:
  #     - 'dev'
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
  #     - queue
  #   volumes:
  #     - .:/usr/app

  # prod:
  #   container_name: 'adoptgram-social-prod'
  #   build:
  #     context: .
  #     dockerfile: prod.Dockerfile
  #   profiles:
  #     - 'prod'
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
  #     - queue
